#! /usr/local/bin/python3

import pyperclip, sys, os

hazelFilePath = sys.argv[1]
pyperclip.copy(hazelFilePath)

# Copy only the filename (excluding the full path)
pyperclip.copy(os.path.basename(hazelFilePath))